stages:      
  - lint    
  - build
  - test
  - deploy

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .tox/
    - venv/

default:
  before_script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install tox

lint_job:
  stage: lint
  # Official language image. Look for the different tagged releases at:
  # https://hub.docker.com/r/library/python/tags/
  image: python:${PYTHON_VERSION}
  script:
    - tox -e ${TOXENV}
  parallel:
    matrix:
      - PYTHON_VERSION: "3.10"
        TOXENV: [bandit, black, flake8]

test_job:
  stage: test
  when: on_success
  # Official language image. Look for the different tagged releases at:
  # https://hub.docker.com/r/library/python/tags/
  image: python:${PYTHON_VERSION}
  script:
    - tox -e ${TOXENV}
  parallel:
    matrix:
      - PYTHON_VERSION: "3.8"
        TOXENV: [py38]
      - PYTHON_VERSION: "3.9"
        TOXENV: [py39]
      - PYTHON_VERSION: "3.10"
        TOXENV: [py310]
