name: Code Coverage
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code coverage
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pytest
        run: pip install pytest-cov
      - name: Install poetry
        run: pip install poetry
      - name: Configure poetry
        run: poetry config virtualenvs.create false
      - name: Install dependencies
        run: poetry install
      - name: Run tests and collect coverage
        run: coverage run --omit="./tests" -m pytest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: IFCA-Advanced-Computing/anjana
